### ISSUE TITLE
Problem with monitor in Mac

### ISSUE THREAD

**Issue by PoriNiki** [agentcontest/massim#7]
Hi. I'm new in MASSIM. while I run the server in windows platform there is no problem but as I run the server in my mac system when I just use monitor option I get an error and couldn't find the solution why.
I use this command to run the server in terminal :
```
java -jar server-2017-0.7-jar-with-dependencies.jar --monitor 8000
```
and there will be no problem without monitor option.
this is the exact error:
```
java.lang.IllegalArgumentException: Malformed IPv6 address at index 8: http://[USER]:8000/
	at java.net.URI.create(URI.java:852)
	at org.webbitserver.netty.NettyWebServer.localUri(NettyWebServer.java:338)
	at org.webbitserver.netty.NettyWebServer.<init>(NettyWebServer.java:85)
	at org.webbitserver.netty.NettyWebServer.<init>(NettyWebServer.java:79)
	at org.webbitserver.netty.NettyWebServer.<init>(NettyWebServer.java:75)
	at org.webbitserver.WebServers.createWebServer(WebServers.java:19)
	at massim.monitor.Monitor.<init>(Monitor.java:56)
	at massim.Server.go(Server.java:181)
	at massim.Server.main(Server.java:135)
Caused by: java.net.URISyntaxException: Malformed IPv6 address at index 8: http://[USER]:8000/
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseIPv6Reference(URI.java:3469)
	at java.net.URI$Parser.parseServer(URI.java:3219)
	at java.net.URI$Parser.parseAuthority(URI.java:3155)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 8 more
```

**Comment by niklasf** [comment]
Hi, thanks for reporting this bug. I attempted to fix it (or rather work around it) via cc9e87613f36cdb6534c6794cc8076ded83e5bbf.
