### ISSUE TITLE
Problem starting EIS connection

### ISSUE THREAD

**Issue by remcollier** [agentcontest/massim#9]
Hi,

I am getting a class not found exception when I try to load the EIS environment, specifically:

Class "massim.javaagents.Main" could not be loaded from "eismassim-3.5-jar-with-dependencies.jar"

I'm just wondering whether I am doing something wrong (I am using EIS 0.5)

Thanks

Rem

EDIT: Just to add - I am using Eclipse and my own AOP language (ASTRA) to try to connect (everything works fine with MASSIM-2017-1.7)

**Comment by t-ah** [comment]
Hi Rem,

there is no javaagents package in eismassim. Do you mean massim.eismassim.EnvironmentInterface perhaps?

Best regards,
Tobias

**Comment by remcollier** [comment]
Here is the full output (the first line is from ASTRA, and the second exception is as a result of the first exception);

Scheduling Strategy set to: astra.execution.BasicSchedulerStrategy
java.io.IOException: Class "massim.javaagents.Main" could not be loaded from "eismassim-3.5-jar-with-dependencies.jar"
	at eis.EILoader.fromJarFile(EILoader.java:80)
	at astra.eis.EISService.setup(EISService.java:156)
	at astra.eis.EISService.newService(EISService.java:45)
	at astra.lang.EIS.launch(EIS.java:127)
	at massim.Start$3.invoke(Start.java:81)
	at astra.statement.ModuleCall$1$1.doTask(ModuleCall.java:64)
	at astra.core.AbstractTask.run(AbstractTask.java:27)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: massim.javaagents.Main
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at eis.EILoader.fromJarFile(EILoader.java:78)
	... 11 more
[astra.core.Agent] Ignoring event: -!main([])
Failed Action: eis.join()
massim.Start.join():12
+!main([])
Caused By:
java.lang.NullPointerException
	at astra.eis.EISService.registerAgent(EISService.java:179)
	at astra.eis.EISAgent.<init>(EISAgent.java:140)
	at astra.lang.EIS.join(EIS.java:228)
	at massim.Start$4.invoke(Start.java:97)
	at astra.statement.ModuleCall$1$1.doTask(ModuleCall.java:64)
	at astra.core.AbstractTask.run(AbstractTask.java:27)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by t-ah** [comment]
Oh I see. The main class for the eismassim build was set incorrectly (and for some reason that hasn't been a problem before).
Can you check if the new version (db9e485c5a150e2193a439760314dbd44c19b41e) works for you?
Thanks.

**Comment by remcollier** [comment]
Please could you build locally and send be the jar because I am having problems with npm install (using ubuntu for windows 10) when executing mvn package. It fails on the monitor stage.

[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ protocol ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building monitor 2018-1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- frontend-maven-plugin:1.4:install-node-and-npm (default) @ monitor ---
[INFO] Node v7.8.0 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:1.4:npm (default) @ monitor ---
[INFO] Running 'npm install' in /mnt/c/Development/massim-master/monitor
[WARNING] npm WARN deprecated openlayers@4.6.5: Please use the ol package instead
[WARNING] npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
[WARNING] npm WARN deprecated uws@9.14.0: stop using this version
[WARNING] npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[WARNING] npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[WARNING] npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[ERROR] npm ERR! tar.unpack untar error /home/rem/.npm/micromatch/2.3.11/package.tgz

**Comment by remcollier** [comment]
Unzipped the jar and updated the Manifest File- everything works now!

**Comment by t-ah** [comment]
Please try the [development snapshot](https://s3-eu-west-1.amazonaws.com/agentcontest/massim/massim-master.tar.gz). It should be up-to-date.

**Comment by remcollier** [comment]
The snapshot also works! Thanks

**Comment by t-ah** [comment]
Great!
(I somehow removed the comment, here's the [development snapshot](https://s3-eu-west-1.amazonaws.com/agentcontest/massim/massim-master.tar.gz) again.)
